Repository dev-trailblazers/studyroom-frontend, pull requests merged in 2024-08, with the labels that each got.

#33 refactor: Home 페이지 컴포넌트 분리
  package-lock.json
  package.json
  public/StudyRoom.svg
  public/logo.svg
  src/App.tsx
  src/components/common/button/Button.tsx
  src/components/common/input/Input.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/select/Select.tsx
  src/components/common/tooltip/Tooltip.tsx
  src/components/index.js
  src/components/layout/footer/Footer.tsx
  src/components/layout/header/Header.tsx
  src/components/pages/Home/InStudy/InStudy.tsx
  src/components/pages/Home/InStudy/InStudyCard.tsx
  src/components/pages/Home/InStudy/InStudyContent.tsx
  src/components/pages/Home/InStudy/InStudyHeader.tsx
  src/components/pages/Home/Notification/Notification.tsx
  src/components/pages/Home/Notification/NotificationContent.tsx
  src/components/pages/Home/Notification/NotificationHeader.tsx
  src/components/pages/Home/Notification/NotificationItem.tsx
  src/components/pages/Home/Notification/NotificationList.tsx
  src/components/pages/Home/Notification/Pagination.tsx
  src/components/pages/Home/RecruitStudy/RecruitStudy.tsx
  src/components/pages/Home/RecruitStudy/RecruitStudyCard.tsx
  src/components/pages/Home/RecruitStudy/RecruitStudyContent.tsx
  src/components/pages/Home/RecruitStudy/RecruitStudyHeader.tsx
  src/components/pages/Home/StudyModal/CreateStudyModal.tsx
  src/components/pages/Home/StudyModal/StudyModal.tsx
  src/data/Notifications.tsx
  src/data/inStudyCards.tsx
  src/data/inStudyData.json
  src/data/notificationData.json
  src/data/recruitStudyData.json
  src/data/recuritStudyCards.tsx
  src/data/recuritStudyModal.tsx
  src/hooks/useInStudies.ts
  src/hooks/useModals.ts
  src/hooks/useNotifications.ts
  src/hooks/useRecruitingStudies.ts
  src/index.css
  src/pages/auth/sign-in/SignIn.tsx
  src/pages/home/Home.tsx
  src/pages/home/Main_BackUp.tsx
  src/pages/home/Mypage.tsx
  src/pages/index.js
  src/pages/mypage/Mypage.tsx
  src/pages/notice/Notice.tsx
  src/pages/notice/Notice_BackUp.tsx
  src/types/Notification.ts
  tsconfig.json
  vite.config.ts
Labels: ✨Feature, 🔨Refactor

#34 [fix] 최신화 및 충돌 해결
  index.html
  src/App.tsx
  src/apis/useApi.tsx
  src/components/common/input/Input.tsx
  src/components/common/select/Select.tsx
  src/data/index.js
  src/pages/auth/sign-in/SignIn.tsx
  src/pages/auth/sign-up/SignUp.tsx
  src/pages/notice/Notice_BackUp.tsx
  src/utils/checkEmptyObject.tsx
  src/utils/index.js
  src/utils/onChangeObjectInput.tsx
  src/utils/updateObjectState.tsx
  vite.config.ts
Labels: ✨Feature, 🔨Refactor

#35 Refactor: Home 페이지 리팩토링
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/circlebutton/CircleButton.tsx
  src/components/common/input/Input.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/select/Select.tsx
  src/components/index.js
  src/components/layout/header/Header.tsx
  src/components/layout/sidebar/SideBar.tsx
  src/components/pages/Home/InStudy/InStudy.tsx
  src/components/pages/Home/InStudy/InStudyCard.tsx
  src/components/pages/Home/InStudy/InStudyContent.tsx
  src/components/pages/Home/InStudy/InStudyHeader.tsx
  src/components/pages/Home/Notification/NotificationItem.tsx
  src/components/pages/Home/RecruitStudy/RecruitStudy.tsx
  src/components/pages/Home/RecruitStudy/RecruitStudyCard.tsx
  src/components/pages/Home/RecruitStudy/RecruitStudyHeader.tsx
  src/components/pages/Home/StudyModal/CreateStudyModal.tsx
  src/components/pages/Home/StudyModal/StudyModal.tsx
  src/components/pages/Home/createStudyModal/CreateStudyModal.tsx
  src/components/pages/Home/recruitstudymodal/RecruitStudyModal.tsx
  src/contexts/ModalContext.tsx
  src/data/index.js
  src/hooks/useModal.ts
  src/hooks/useModalContext.ts
  src/hooks/useModals.ts
  src/pages/home/Home.tsx
  src/pages/home/Main_BackUp.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/notice/Notice.tsx
  src/pages/notice/Notice_BackUp.tsx
  src/styles/theme.js
  src/types/InStudy.ts
  src/types/RecruitStudy.ts
  tailwind.config.js
  tsconfig.json
  vite.config.ts
Labels: ✨Feature, 🎨Html&css, 🔨Refactor

#36 Styles : Input, Select 컴포넌트 커스텀 / Merge : home 리팩토링 코드 합병
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/input/Input.tsx
  src/components/common/select/Select.tsx
  src/components/index.js
  src/components/layout/header/Header.tsx
  src/pages/auth/sign-in/SignIn.tsx
  src/pages/auth/sign-up/SignUp.tsx
  tailwind.config.js
  tsconfig.json
  vite.config.ts
Labels: ✨Feature, 🔨Refactor

#37 [feat] useModal hook 사용하여 회원가입 이메일 인증 모달 수정
  src/pages/auth/sign-up/SignUp.tsx
Labels: ✨Feature

#38 스터디 생성 모달 및 스터디 모집 모달 마크업 및 input, select 컴포넌트 마크업 수정
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/apis/useApi.tsx
  src/components/common/circlebutton/CircleButton.tsx
  src/components/common/input/Input.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/select/Select.tsx
  src/components/index.js
  src/components/layout/header/Header.tsx
  src/components/layout/sidebar/SideBar.tsx
  src/components/pages/Home/InStudy/InStudy.tsx
  src/components/pages/Home/InStudy/InStudyCard.tsx
  src/components/pages/Home/InStudy/InStudyContent.tsx
  src/components/pages/Home/InStudy/InStudyHeader.tsx
  src/components/pages/Home/Notification/NotificationItem.tsx
  src/components/pages/Home/RecruitStudy/RecruitStudy.tsx
  src/components/pages/Home/RecruitStudy/RecruitStudyCard.tsx
  src/components/pages/Home/RecruitStudy/RecruitStudyHeader.tsx
  src/components/pages/Home/StudyModal/CreateStudyModal.tsx
  src/components/pages/Home/StudyModal/StudyModal.tsx
  src/components/pages/Home/createStudyModal/CreateStudyModal.tsx
  src/components/pages/Home/recruitstudymodal/RecruitStudyModal.tsx
  src/contexts/ModalContext.tsx
  src/data/index.js
  src/hooks/useModal.ts
  src/hooks/useModalContext.ts
  src/hooks/useModals.ts
  src/pages/auth/sign-in/SignIn.tsx
  src/pages/auth/sign-up/SignUp.tsx
  src/pages/home/Home.tsx
  src/pages/home/Main_BackUp.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/notice/Notice.tsx
  src/pages/notice/Notice_BackUp.tsx
  src/styles/theme.js
  src/types/InStudy.ts
  src/types/RecruitStudy.ts
  src/utils/checkEmptyObject.tsx
  src/utils/index.js
  src/utils/onChangeObjectInput.tsx
  src/utils/updateObjectState.tsx
  tailwind.config.js
  tsconfig.json
  vite.config.ts
Labels: ✨Feature, 🎨Html&css
